class_name RunSnapshot
extends RefCounted

static func make(controller: Node, world: Node, warden: Node, health: Node, spawner: Node, inventory: Node) -> Dictionary:
	var health_current := float(health.current_health) if health else 0.0
	var health_maximum := float(health.maximum_health) if health else 0.0
	var wave_snapshot: Dictionary = controller.wave_director.get_snapshot()
	var wave_definition: Dictionary = wave_snapshot.get("definition", {})
	var ledger_snapshot: Dictionary = controller.complete_run_ledger.get_snapshot() if controller.complete_run_ledger else {}
	var ledger_matrix: Dictionary = ledger_snapshot.get("matrix", {})
	return {
		"serial": int(controller.run_serial),
		"state": String(controller.run_state),
		"elapsed": float(controller.run_elapsed),
		"health": health_current,
		"health_maximum": health_maximum,
		"experience": int(controller.experience),
		"experience_threshold": int(controller.experience_threshold),
		"level": int(controller.level),
		"defeated": int(controller.defeated_enemies),
		"damage_taken": int(controller.damage_taken),
		"encounter": spawner.get_snapshot() if spawner else {},
		"weapons": inventory.get_snapshot() if inventory else {},
		"dash_phase": String(warden.dash_phase) if warden else "ready",
		"dash_remaining": float(warden.dash_cooldown_remaining) if warden else 0.0,
		"dash_duration": float(warden.cooldown_duration) if warden else 1.0,
		"pickup_collection_radius":float(warden.pickup_collection_radius) if warden else 1.75,
		"experience_yield_multiplier":float(warden.experience_yield_multiplier) if warden else 1.0,
		"wave": int(wave_snapshot.get("wave",1)),
		"wave_count": int(wave_snapshot.get("wave_count",5)),
		"wave_id": String(wave_definition.get("id","warmup")),
		"wave_title": String(wave_snapshot.get("title","WARMUP")),
		"wave_elapsed": float(wave_snapshot.get("wave_elapsed",0.0)),
		"wave_duration": float(wave_snapshot.get("wave_duration",0.0)),
		"wave_definition": wave_definition.duplicate(true),
		"ordinary_route_wave_ids":(wave_snapshot.get("ordinary_route_wave_ids", []) as Array).duplicate(),
		"ordinary_route_complete":bool(wave_snapshot.get("ordinary_route_complete", false)),
		"ordinary_route_eligible":String(controller.run_route_kind) == "ordinary" and bool(wave_snapshot.get("ordinary_route_eligible", false)),
		"diagnostic_jump_count":int(wave_snapshot.get("diagnostic_jump_count", 0)),
		"run_route_kind":String(controller.run_route_kind),
		"boss_active": bool(controller.boss_snapshot.get("active",false)),
		"boss_health": float(controller.boss_snapshot.get("health",0.0)),
		"boss_health_maximum": float(controller.boss_snapshot.get("health_maximum",0.0)),
		"boss_phase": int(controller.boss_snapshot.get("phase",1)),
		"boss_state": String(controller.boss_snapshot.get("state","inactive")),
		"boss_vulnerable": bool(controller.boss_snapshot.get("vulnerable",false)),
		"outcome": String(controller.outcome),
		"damage_dealt": int(controller.damage_dealt),
		"selected_upgrades": controller.selected_upgrades.duplicate(true),
		"first_run_guidance":controller._first_run_guidance_snapshot(),
		"reward_feedback":controller._reward_feedback_snapshot(),
		"warden_animation": warden.animation_binding.get_snapshot() if warden and warden.animation_binding else {},
		"warden_movement": warden.get_movement_snapshot() if warden else {},
		"terminal_reset_invariants": controller._terminal_reset_invariants("snapshot"),
		"upgrade_draft": controller.draft_controller.get_snapshot(),
		"teardown_receipt": controller.teardown_receipt.duplicate(true),
		"pause_ownership": {
			"tree_paused":controller.get_tree().paused,
			"controller_process_mode":controller.process_mode,
			"shell_process_mode":controller.shell.process_mode,
			"world_process_mode":world.process_mode if world else Node.PROCESS_MODE_DISABLED,
			"wave_process_mode":controller.wave_director.process_mode,
		},
		"terminal_handoff":controller.terminal_handoff_receipt.duplicate(true),
		"context_handoff":controller.context_handoff_receipt.duplicate(true),
		"validation_density":controller.validation_density_receipt.duplicate(true),
		"validation_profile":controller.validation_profile_receipt.duplicate(true),
		"validation_profile_sample":controller.validation_profile_sample.duplicate(true),
		"validation_profile_cycles":controller.validation_profile_cycles.duplicate(true),
		"ordinary_profile_cycles":controller.ordinary_profile_cycles.duplicate(true),
		"validation_profile_cycle_comparison":controller._profile_cycle_comparison(),
		"ordinary_profile_contract_checks":controller.ordinary_profile_contract_checks.duplicate(true),
		"validation_retry_baselines":controller.validation_retry_baselines.duplicate(true),
		"boss_transition_history":controller.boss_transition_history.duplicate(true),
		"ordinary_victory_receipt":controller.ordinary_victory_receipt.duplicate(true),
		"tester_victory_fixture":controller.tester_victory_fixture_receipt.duplicate(true),
		"warden_hat_isolation":warden.hat_isolation_receipt.duplicate(true) if warden else {},
		"complete_run_ledger":ledger_snapshot,
		"complete_run_row_qualifications":(ledger_matrix.get("row_qualifications", []) as Array).duplicate(true),
		"complete_run_build_shape_rows":(ledger_matrix.get("ordinary_build_shape_rows", {}) as Dictionary).duplicate(true),
		"complete_run_remaining_matrix_cells":(ledger_matrix.get("remaining_matrix_cells", []) as Array).duplicate(),
		"validation_profile_matrix":controller._profile_matrix_snapshot(),
		"world_active": world.session_active if world else false,
	}
